name          'alphagov-heka'
version       '0.2.0'
source        'https://github.com/alphagov/puppet-heka'
author        'Government Digital Service'
license       'MIT'
summary       'Puppet module for Heka'
description   'Puppet module for Heka'
project_page  'https://github.com/alphagov/puppet-heka'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
